"""create interviews table

Revision ID: f332efdd5311
Revises: 73269d0aa8fe
Create Date: 2026-07-30 19:05:46.384971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f332efdd5311'
down_revision: Union[str, Sequence[str], None] = '73269d0aa8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('technical_questions', sa.JSON(), nullable=False))
    op.add_column('interviews', sa.Column('hr_questions', sa.JSON(), nullable=False))
    op.add_column('interviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('interviews', 'questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('interviews', 'created_at')
    op.drop_column('interviews', 'hr_questions')
    op.drop_column('interviews', 'technical_questions')
    # ### end Alembic commands ###
