"""create resume summaries table

Revision ID: f338bd677fc1
Revises: 1b6dc9aabae0
Create Date: 2026-08-01 21:40:51.727148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f338bd677fc1'
down_revision: Union[str, Sequence[str], None] = '1b6dc9aabae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('top_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hire_decision', sa.String(), nullable=False),
    sa.Column('overall_summary', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_summaries_id'), 'resume_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_summaries_id'), table_name='resume_summaries')
    op.drop_table('resume_summaries')
    # ### end Alembic commands ###
